import type { AccountAuthenticator } from "@aptos-labs/ts-sdk"

export type ToolsNameList =
	| "aptos_balance"
	| "aptos_get_wallet_address"
	| "aptos_transfer_token"
	| "aptos_burn_token"
	| "aptos_get_transaction"
	| "aptos_get_transaction_history"
	| "aptos_token_details"
	| "aptos_mint_token"
	| "aptos_create_token"
	| "aptos_token_price"
	| "amnis_stake"
	| "amnis_withdraw_stake"
	| "joule_lend_token"
	| "joule_withdraw_token"
	| "joule_borrow_token"
	| "joule_repay_token"
	| "joule_get_pool_details"
	| "joule_get_user_position"
	| "joule_get_user_all_positions"
	| "liquidswap_add_liquidity"
	| "liquidswap_create_pool"
	| "liquidswap_remove_liquidity"
	| "liquidswap_swap"
	| "aries_create_profile"
	| "aries_withdraw"
	| "aries_borrow"
	| "aries_lend"
	| "aries_repay"
	| "thala_add_liquidity"
	| "thala_remove_liquidity"
	| "thala_mint_mod"
	| "thala_redeem_mod"
	| "thala_unstake_token"
	| "thala_stake_token"
	| "panora_aggregator_swap"
	| "panora_aggregator_price"
	| "panora_aggregator_list"
	| "openai_create_image"
	| "echo_stake_token"
	| "echo_unstake_token"
	| "echelon_lend_token"
	| "echelon_withdraw_token"
	| "echelon_borrow_token"
	| "echelon_repay_token"
	| "merkle_trade_place_market_order"
	| "merkle_trade_place_limit_order"
	| "merkle_trade_close_position"
	| "merkle_trade_get_position"
	| "emojicoin_get_market"
	| "emojicoin_swap"
	| "emojicoin_provide_liquidity"
	| "emojicoin_remove_liquidity"
	| "emojicoin_register_market"

export type SignedTransactionResponse = {
	senderAuthenticator?: AccountAuthenticator
	signature?: Uint8Array<ArrayBufferLike>
}
// cspell:disable

const SYMBOL_EMOJIS = {
	"🥇": "1st place medal",
	"🥈": "2nd place medal",
	"🥉": "3rd place medal",
	"🅰️": "A button (blood type)",
	"🆎": "AB button (blood type)",
	"🏧": "ATM sign",
	"♒": "Aquarius",
	"♈": "Aries",
	"🅱️": "B button (blood type)",
	"🔙": "BACK arrow",
	"🆑": "CL button",
	"🆒": "COOL button",
	"♋": "Cancer",
	"♑": "Capricorn",
	"🎄": "Christmas tree",
	"🔚": "END arrow",
	"🆓": "FREE button",
	"♊": "Gemini",
	"🆔": "ID button",
	"🉑": 'Japanese "acceptable" button',
	"🈸": 'Japanese "application" button',
	"🉐": 'Japanese "bargain" button',
	"㊗️": 'Japanese "congratulations" button',
	"🈹": 'Japanese "discount" button',
	"🈚": 'Japanese "free of charge" button',
	"🈁": 'Japanese "here" button',
	"🈷️": 'Japanese "monthly amount" button',
	"🈵": 'Japanese "no vacancy" button',
	"🈶": 'Japanese "not free of charge" button',
	"🈺": 'Japanese "open for business" button',
	"🈴": 'Japanese "passing grade" button',
	"🈲": 'Japanese "prohibited" button',
	"🈯": 'Japanese "reserved" button',
	"㊙️": 'Japanese "secret" button',
	"🈂️": 'Japanese "service charge" button',
	"🈳": 'Japanese "vacancy" button',
	"🏯": "Japanese castle",
	"🎎": "Japanese dolls",
	"🏣": "Japanese post office",
	"🔰": "Japanese symbol for beginner",
	"♌": "Leo",
	"♎": "Libra",
	"🤶": "Mrs. Claus",
	"🤶🏿": "Mrs. Claus: dark skin tone",
	"🤶🏻": "Mrs. Claus: light skin tone",
	"🤶🏽": "Mrs. Claus: medium skin tone",
	"🤶🏾": "Mrs. Claus: medium-dark skin tone",
	"🤶🏼": "Mrs. Claus: medium-light skin tone",
	"🆕": "NEW button",
	"🆖": "NG button",
	"🅾️": "O button (blood type)",
	"🆗": "OK button",
	"👌": "OK hand",
	"👌🏿": "OK hand: dark skin tone",
	"👌🏻": "OK hand: light skin tone",
	"👌🏽": "OK hand: medium skin tone",
	"👌🏾": "OK hand: medium-dark skin tone",
	"👌🏼": "OK hand: medium-light skin tone",
	"🔛": "ON! arrow",
	"⛎": "Ophiuchus",
	"🅿️": "P button",
	"♓": "Pisces",
	"🔜": "SOON arrow",
	"🆘": "SOS button",
	"♐": "Sagittarius",
	"🎅": "Santa Claus",
	"🎅🏿": "Santa Claus: dark skin tone",
	"🎅🏻": "Santa Claus: light skin tone",
	"🎅🏽": "Santa Claus: medium skin tone",
	"🎅🏾": "Santa Claus: medium-dark skin tone",
	"🎅🏼": "Santa Claus: medium-light skin tone",
	"♏": "Scorpio",
	"🗽": "Statue of Liberty",
	"🦖": "T-Rex",
	"🔝": "TOP arrow",
	"♉": "Taurus",
	"🗼": "Tokyo tower",
	"🆙": "UP! button",
	"🆚": "VS button",
	"♍": "Virgo",
	"💤": "ZZZ",
	"🧮": "abacus",
	"🪗": "accordion",
	"🩹": "adhesive bandage",
	"🎟️": "admission tickets",
	"🚡": "aerial tramway",
	"✈️": "airplane",
	"🛬": "airplane arrival",
	"🛫": "airplane departure",
	"⏰": "alarm clock",
	"⚗️": "alembic",
	"👽": "alien",
	"👾": "alien monster",
	"🚑": "ambulance",
	"🏈": "american football",
	"🏺": "amphora",
	"🫀": "anatomical heart",
	"⚓": "anchor",
	"💢": "anger symbol",
	"😠": "angry face",
	"👿": "angry face with horns",
	"😧": "anguished face",
	"🐜": "ant",
	"📶": "antenna bars",
	"😰": "anxious face with sweat",
	"🚛": "articulated lorry",
	"🎨": "artist palette",
	"😲": "astonished face",
	"⚛️": "atom symbol",
	"🛺": "auto rickshaw",
	"🚗": "automobile",
	"🥑": "avocado",
	"🪓": "axe",
	"👶": "baby",
	"👼": "baby angel",
	"👼🏿": "baby angel: dark skin tone",
	"👼🏻": "baby angel: light skin tone",
	"👼🏽": "baby angel: medium skin tone",
	"👼🏾": "baby angel: medium-dark skin tone",
	"👼🏼": "baby angel: medium-light skin tone",
	"🍼": "baby bottle",
	"🐤": "baby chick",
	"🚼": "baby symbol",
	"👶🏿": "baby: dark skin tone",
	"👶🏻": "baby: light skin tone",
	"👶🏽": "baby: medium skin tone",
	"👶🏾": "baby: medium-dark skin tone",
	"👶🏼": "baby: medium-light skin tone",
	"👇": "backhand index pointing down",
	"👇🏿": "backhand index pointing down: dark skin tone",
	"👇🏻": "backhand index pointing down: light skin tone",
	"👇🏽": "backhand index pointing down: medium skin tone",
	"👇🏾": "backhand index pointing down: medium-dark skin tone",
	"👇🏼": "backhand index pointing down: medium-light skin tone",
	"👈": "backhand index pointing left",
	"👈🏿": "backhand index pointing left: dark skin tone",
	"👈🏻": "backhand index pointing left: light skin tone",
	"👈🏽": "backhand index pointing left: medium skin tone",
	"👈🏾": "backhand index pointing left: medium-dark skin tone",
	"👈🏼": "backhand index pointing left: medium-light skin tone",
	"👉": "backhand index pointing right",
	"👉🏿": "backhand index pointing right: dark skin tone",
	"👉🏻": "backhand index pointing right: light skin tone",
	"👉🏽": "backhand index pointing right: medium skin tone",
	"👉🏾": "backhand index pointing right: medium-dark skin tone",
	"👉🏼": "backhand index pointing right: medium-light skin tone",
	"👆": "backhand index pointing up",
	"👆🏿": "backhand index pointing up: dark skin tone",
	"👆🏻": "backhand index pointing up: light skin tone",
	"👆🏽": "backhand index pointing up: medium skin tone",
	"👆🏾": "backhand index pointing up: medium-dark skin tone",
	"👆🏼": "backhand index pointing up: medium-light skin tone",
	"🎒": "backpack",
	"🥓": "bacon",
	"🦡": "badger",
	"🏸": "badminton",
	"🥯": "bagel",
	"🛄": "baggage claim",
	"🥖": "baguette bread",
	"⚖️": "balance scale",
	"🩰": "ballet shoes",
	"🎈": "balloon",
	"🗳️": "ballot box with ballot",
	"🍌": "banana",
	"🪕": "banjo",
	"🏦": "bank",
	"📊": "bar chart",
	"💈": "barber pole",
	"⚾": "baseball",
	"🧺": "basket",
	"🏀": "basketball",
	"🦇": "bat",
	"🛁": "bathtub",
	"🔋": "battery",
	"🏖️": "beach with umbrella",
	"😁": "beaming face with smiling eyes",
	"🫘": "beans",
	"🐻": "bear",
	"💓": "beating heart",
	"🦫": "beaver",
	"🛏️": "bed",
	"🍺": "beer mug",
	"🪲": "beetle",
	"🔔": "bell",
	"🫑": "bell pepper",
	"🔕": "bell with slash",
	"🛎️": "bellhop bell",
	"🍱": "bento box",
	"🧃": "beverage box",
	"🚲": "bicycle",
	"👙": "bikini",
	"🧢": "billed cap",
	"☣️": "biohazard",
	"🐦": "bird",
	"🎂": "birthday cake",
	"🦬": "bison",
	"🫦": "biting lip",
	"🐦‍⬛": "black bird",
	"🐈‍⬛": "black cat",
	"⚫": "black circle",
	"🏴": "black flag",
	"🖤": "black heart",
	"⬛": "black large square",
	"◼️": "black medium square",
	"◾": "black medium-small square",
	"✒️": "black nib",
	"▪️": "black small square",
	"🔲": "black square button",
	"🌼": "blossom",
	"🐡": "blowfish",
	"📘": "blue book",
	"🔵": "blue circle",
	"💙": "blue heart",
	"🟦": "blue square",
	"🫐": "blueberries",
	"🐗": "boar",
	"💣": "bomb",
	"🦴": "bone",
	"🔖": "bookmark",
	"📑": "bookmark tabs",
	"📚": "books",
	"🪃": "boomerang",
	"🍾": "bottle with popping cork",
	"💐": "bouquet",
	"🏹": "bow and arrow",
	"🥣": "bowl with spoon",
	"🎳": "bowling",
	"🥊": "boxing glove",
	"👦": "boy",
	"👦🏿": "boy: dark skin tone",
	"👦🏻": "boy: light skin tone",
	"👦🏽": "boy: medium skin tone",
	"👦🏾": "boy: medium-dark skin tone",
	"👦🏼": "boy: medium-light skin tone",
	"🧠": "brain",
	"🍞": "bread",
	"🤱": "breast-feeding",
	"🤱🏿": "breast-feeding: dark skin tone",
	"🤱🏻": "breast-feeding: light skin tone",
	"🤱🏽": "breast-feeding: medium skin tone",
	"🤱🏾": "breast-feeding: medium-dark skin tone",
	"🤱🏼": "breast-feeding: medium-light skin tone",
	"🧱": "brick",
	"🌉": "bridge at night",
	"💼": "briefcase",
	"🩲": "briefs",
	"🔆": "bright button",
	"🥦": "broccoli",
	"💔": "broken heart",
	"🧹": "broom",
	"🟤": "brown circle",
	"🤎": "brown heart",
	"🟫": "brown square",
	"🧋": "bubble tea",
	"🫧": "bubbles",
	"🪣": "bucket",
	"🐛": "bug",
	"🏗️": "building construction",
	"🚅": "bullet train",
	"🎯": "bullseye",
	"🌯": "burrito",
	"🚌": "bus",
	"🚏": "bus stop",
	"👤": "bust in silhouette",
	"👥": "busts in silhouette",
	"🧈": "butter",
	"🦋": "butterfly",
	"🌵": "cactus",
	"📅": "calendar",
	"🤙": "call me hand",
	"🤙🏿": "call me hand: dark skin tone",
	"🤙🏻": "call me hand: light skin tone",
	"🤙🏽": "call me hand: medium skin tone",
	"🤙🏾": "call me hand: medium-dark skin tone",
	"🤙🏼": "call me hand: medium-light skin tone",
	"🐪": "camel",
	"📷": "camera",
	"📸": "camera with flash",
	"🏕️": "camping",
	"🕯️": "candle",
	"🍬": "candy",
	"🥫": "canned food",
	"🛶": "canoe",
	"🗃️": "card file box",
	"📇": "card index",
	"🗂️": "card index dividers",
	"🎠": "carousel horse",
	"🎏": "carp streamer",
	"🪚": "carpentry saw",
	"🥕": "carrot",
	"🏰": "castle",
	"🐈": "cat",
	"🐱": "cat face",
	"😹": "cat with tears of joy",
	"😼": "cat with wry smile",
	"⛓️": "chains",
	"🪑": "chair",
	"📉": "chart decreasing",
	"📈": "chart increasing",
	"💹": "chart increasing with yen",
	"☑️": "check box with check",
	"✔️": "check mark",
	"✅": "check mark button",
	"🧀": "cheese wedge",
	"🏁": "chequered flag",
	"🍒": "cherries",
	"🌸": "cherry blossom",
	"♟️": "chess pawn",
	"🌰": "chestnut",
	"🐔": "chicken",
	"🧒": "child",
	"🧒🏿": "child: dark skin tone",
	"🧒🏻": "child: light skin tone",
	"🧒🏽": "child: medium skin tone",
	"🧒🏾": "child: medium-dark skin tone",
	"🧒🏼": "child: medium-light skin tone",
	"🚸": "children crossing",
	"🐿️": "chipmunk",
	"🍫": "chocolate bar",
	"🥢": "chopsticks",
	"⛪": "church",
	"🚬": "cigarette",
	"🎦": "cinema",
	"Ⓜ️": "circled M",
	"🎪": "circus tent",
	"🏙️": "cityscape",
	"🌆": "cityscape at dusk",
	"🗜️": "clamp",
	"🎬": "clapper board",
	"👏": "clapping hands",
	"👏🏿": "clapping hands: dark skin tone",
	"👏🏻": "clapping hands: light skin tone",
	"👏🏽": "clapping hands: medium skin tone",
	"👏🏾": "clapping hands: medium-dark skin tone",
	"👏🏼": "clapping hands: medium-light skin tone",
	"🏛️": "classical building",
	"🍻": "clinking beer mugs",
	"🥂": "clinking glasses",
	"📋": "clipboard",
	"🔃": "clockwise vertical arrows",
	"📕": "closed book",
	"📪": "closed mailbox with lowered flag",
	"📫": "closed mailbox with raised flag",
	"🌂": "closed umbrella",
	"☁️": "cloud",
	"🌩️": "cloud with lightning",
	"⛈️": "cloud with lightning and rain",
	"🌧️": "cloud with rain",
	"🌨️": "cloud with snow",
	"🤡": "clown face",
	"♣️": "club suit",
	"👝": "clutch bag",
	"🧥": "coat",
	"🪳": "cockroach",
	"🍸": "cocktail glass",
	"🥥": "coconut",
	"⚰️": "coffin",
	"🪙": "coin",
	"🥶": "cold face",
	"💥": "collision",
	"☄️": "comet",
	"🧭": "compass",
	"💽": "computer disk",
	"🖱️": "computer mouse",
	"🎊": "confetti ball",
	"😖": "confounded face",
	"😕": "confused face",
	"🚧": "construction",
	"👷": "construction worker",
	"👷🏿": "construction worker: dark skin tone",
	"👷🏻": "construction worker: light skin tone",
	"👷🏽": "construction worker: medium skin tone",
	"👷🏾": "construction worker: medium-dark skin tone",
	"👷🏼": "construction worker: medium-light skin tone",
	"🎛️": "control knobs",
	"🏪": "convenience store",
	"🍚": "cooked rice",
	"🍪": "cookie",
	"🍳": "cooking",
	"©️": "copyright",
	"🪸": "coral",
	"🛋️": "couch and lamp",
	"🔄": "counterclockwise arrows button",
	"💑": "couple with heart",
	"💑🏿": "couple with heart: dark skin tone",
	"💑🏻": "couple with heart: light skin tone",
	"💑🏽": "couple with heart: medium skin tone",
	"💑🏾": "couple with heart: medium-dark skin tone",
	"💑🏼": "couple with heart: medium-light skin tone",
	"🐄": "cow",
	"🐮": "cow face",
	"🤠": "cowboy hat face",
	"🦀": "crab",
	"🖍️": "crayon",
	"💳": "credit card",
	"🌙": "crescent moon",
	"🦗": "cricket",
	"🏏": "cricket game",
	"🐊": "crocodile",
	"🥐": "croissant",
	"❌": "cross mark",
	"❎": "cross mark button",
	"🤞": "crossed fingers",
	"🤞🏿": "crossed fingers: dark skin tone",
	"🤞🏻": "crossed fingers: light skin tone",
	"🤞🏽": "crossed fingers: medium skin tone",
	"🤞🏾": "crossed fingers: medium-dark skin tone",
	"🤞🏼": "crossed fingers: medium-light skin tone",
	"🎌": "crossed flags",
	"⚔️": "crossed swords",
	"👑": "crown",
	"🩼": "crutch",
	"😿": "crying cat",
	"😢": "crying face",
	"🔮": "crystal ball",
	"🥒": "cucumber",
	"🥤": "cup with straw",
	"🧁": "cupcake",
	"🥌": "curling stone",
	"➰": "curly loop",
	"💱": "currency exchange",
	"🍛": "curry rice",
	"🍮": "custard",
	"🛃": "customs",
	"🥩": "cut of meat",
	"🌀": "cyclone",
	"🗡️": "dagger",
	"🍡": "dango",
	"💨": "dashing away",
	"🧏": "deaf person",
	"🧏🏿": "deaf person: dark skin tone",
	"🧏🏻": "deaf person: light skin tone",
	"🧏🏽": "deaf person: medium skin tone",
	"🧏🏾": "deaf person: medium-dark skin tone",
	"🧏🏼": "deaf person: medium-light skin tone",
	"🌳": "deciduous tree",
	"🦌": "deer",
	"🚚": "delivery truck",
	"🏬": "department store",
	"🏚️": "derelict house",
	"🏜️": "desert",
	"🏝️": "desert island",
	"🖥️": "desktop computer",
	"🕵️": "detective",
	"🕵🏿": "detective: dark skin tone",
	"🕵🏻": "detective: light skin tone",
	"🕵🏽": "detective: medium skin tone",
	"🕵🏾": "detective: medium-dark skin tone",
	"🕵🏼": "detective: medium-light skin tone",
	"♦️": "diamond suit",
	"💠": "diamond with a dot",
	"🔅": "dim button",
	"😞": "disappointed face",
	"🥸": "disguised face",
	"➗": "divide",
	"🤿": "diving mask",
	"🪔": "diya lamp",
	"💫": "dizzy",
	"🧬": "dna",
	"🦤": "dodo",
	"🐕": "dog",
	"🐶": "dog face",
	"💵": "dollar banknote",
	"🐬": "dolphin",
	"🫏": "donkey",
	"🚪": "door",
	"🫥": "dotted line face",
	"🔯": "dotted six-pointed star",
	"➿": "double curly loop",
	"‼️": "double exclamation mark",
	"🍩": "doughnut",
	"🕊️": "dove",
	"⬇️": "down arrow",
	"↙️": "down-left arrow",
	"↘️": "down-right arrow",
	"😓": "downcast face with sweat",
	"🔽": "downwards button",
	"🐉": "dragon",
	"🐲": "dragon face",
	"👗": "dress",
	"🤤": "drooling face",
	"🩸": "drop of blood",
	"💧": "droplet",
	"🥁": "drum",
	"🦆": "duck",
	"🥟": "dumpling",
	"📀": "dvd",
	"📧": "e-mail",
	"🦅": "eagle",
	"👂": "ear",
	"🌽": "ear of corn",
	"🦻": "ear with hearing aid",
	"🦻🏿": "ear with hearing aid: dark skin tone",
	"🦻🏻": "ear with hearing aid: light skin tone",
	"🦻🏽": "ear with hearing aid: medium skin tone",
	"🦻🏾": "ear with hearing aid: medium-dark skin tone",
	"🦻🏼": "ear with hearing aid: medium-light skin tone",
	"👂🏿": "ear: dark skin tone",
	"👂🏻": "ear: light skin tone",
	"👂🏽": "ear: medium skin tone",
	"👂🏾": "ear: medium-dark skin tone",
	"👂🏼": "ear: medium-light skin tone",
	"🥚": "egg",
	"🍆": "eggplant",
	"🕗": "eight o'clock",
	"✴️": "eight-pointed star",
	"✳️": "eight-spoked asterisk",
	"🕣": "eight-thirty",
	"⏏️": "eject button",
	"🔌": "electric plug",
	"🐘": "elephant",
	"🛗": "elevator",
	"🕚": "eleven o'clock",
	"🕦": "eleven-thirty",
	"🧝": "elf",
	"🧝🏿": "elf: dark skin tone",
	"🧝🏻": "elf: light skin tone",
	"🧝🏽": "elf: medium skin tone",
	"🧝🏾": "elf: medium-dark skin tone",
	"🧝🏼": "elf: medium-light skin tone",
	"🪹": "empty nest",
	"😡": "enraged face",
	"✉️": "envelope",
	"📩": "envelope with arrow",
	"💶": "euro banknote",
	"🌲": "evergreen tree",
	"🐑": "ewe",
	"⁉️": "exclamation question mark",
	"🤯": "exploding head",
	"😑": "expressionless face",
	"👁️": "eye",
	"👀": "eyes",
	"😘": "face blowing a kiss",
	"🥹": "face holding back tears",
	"😋": "face savoring food",
	"😱": "face screaming in fear",
	"🤮": "face vomiting",
	"😵": "face with crossed-out eyes",
	"🫤": "face with diagonal mouth",
	"🤭": "face with hand over mouth",
	"🤕": "face with head-bandage",
	"😷": "face with medical mask",
	"🧐": "face with monocle",
	"🫢": "face with open eyes and hand over mouth",
	"😮": "face with open mouth",
	"🫣": "face with peeking eye",
	"🤨": "face with raised eyebrow",
	"🙄": "face with rolling eyes",
	"😤": "face with steam from nose",
	"🤬": "face with symbols on mouth",
	"😂": "face with tears of joy",
	"🤒": "face with thermometer",
	"😛": "face with tongue",
	"😶": "face without mouth",
	"🏭": "factory",
	"🧚": "fairy",
	"🧚🏿": "fairy: dark skin tone",
	"🧚🏻": "fairy: light skin tone",
	"🧚🏽": "fairy: medium skin tone",
	"🧚🏾": "fairy: medium-dark skin tone",
	"🧚🏼": "fairy: medium-light skin tone",
	"🧆": "falafel",
	"🍂": "fallen leaf",
	"👪": "family",
	"⏬": "fast down button",
	"⏪": "fast reverse button",
	"⏫": "fast up button",
	"⏩": "fast-forward button",
	"📠": "fax machine",
	"😨": "fearful face",
	"🪶": "feather",
	"♀️": "female sign",
	"🎡": "ferris wheel",
	"⛴️": "ferry",
	"🏑": "field hockey",
	"🗄️": "file cabinet",
	"📁": "file folder",
	"🎞️": "film frames",
	"📽️": "film projector",
	"🔥": "fire",
	"🚒": "fire engine",
	"🧯": "fire extinguisher",
	"🧨": "firecracker",
	"🎆": "fireworks",
	"🌓": "first quarter moon",
	"🌛": "first quarter moon face",
	"🐟": "fish",
	"🍥": "fish cake with swirl",
	"🎣": "fishing pole",
	"🕔": "five o'clock",
	"🕠": "five-thirty",
	"⛳": "flag in hole",
	"🇦🇫": "flag: Afghanistan",
	"🇦🇱": "flag: Albania",
	"🇩🇿": "flag: Algeria",
	"🇦🇸": "flag: American Samoa",
	"🇦🇩": "flag: Andorra",
	"🇦🇴": "flag: Angola",
	"🇦🇮": "flag: Anguilla",
	"🇦🇶": "flag: Antarctica",
	"🇦🇬": "flag: Antigua & Barbuda",
	"🇦🇷": "flag: Argentina",
	"🇦🇲": "flag: Armenia",
	"🇦🇼": "flag: Aruba",
	"🇦🇨": "flag: Ascension Island",
	"🇦🇺": "flag: Australia",
	"🇦🇹": "flag: Austria",
	"🇦🇿": "flag: Azerbaijan",
	"🇧🇸": "flag: Bahamas",
	"🇧🇭": "flag: Bahrain",
	"🇧🇩": "flag: Bangladesh",
	"🇧🇧": "flag: Barbados",
	"🇧🇾": "flag: Belarus",
	"🇧🇪": "flag: Belgium",
	"🇧🇿": "flag: Belize",
	"🇧🇯": "flag: Benin",
	"🇧🇲": "flag: Bermuda",
	"🇧🇹": "flag: Bhutan",
	"🇧🇴": "flag: Bolivia",
	"🇧🇦": "flag: Bosnia & Herzegovina",
	"🇧🇼": "flag: Botswana",
	"🇧🇻": "flag: Bouvet Island",
	"🇧🇷": "flag: Brazil",
	"🇮🇴": "flag: British Indian Ocean Territory",
	"🇻🇬": "flag: British Virgin Islands",
	"🇧🇳": "flag: Brunei",
	"🇧🇬": "flag: Bulgaria",
	"🇧🇫": "flag: Burkina Faso",
	"🇧🇮": "flag: Burundi",
	"🇰🇭": "flag: Cambodia",
	"🇨🇲": "flag: Cameroon",
	"🇨🇦": "flag: Canada",
	"🇮🇨": "flag: Canary Islands",
	"🇨🇻": "flag: Cape Verde",
	"🇧🇶": "flag: Caribbean Netherlands",
	"🇰🇾": "flag: Cayman Islands",
	"🇨🇫": "flag: Central African Republic",
	"🇪🇦": "flag: Ceuta & Melilla",
	"🇹🇩": "flag: Chad",
	"🇨🇱": "flag: Chile",
	"🇨🇳": "flag: China",
	"🇨🇽": "flag: Christmas Island",
	"🇨🇵": "flag: Clipperton Island",
	"🇨🇨": "flag: Cocos (Keeling) Islands",
	"🇨🇴": "flag: Colombia",
	"🇰🇲": "flag: Comoros",
	"🇨🇬": "flag: Congo - Brazzaville",
	"🇨🇩": "flag: Congo - Kinshasa",
	"🇨🇰": "flag: Cook Islands",
	"🇨🇷": "flag: Costa Rica",
	"🇭🇷": "flag: Croatia",
	"🇨🇺": "flag: Cuba",
	"🇨🇼": "flag: Curaçao",
	"🇨🇾": "flag: Cyprus",
	"🇨🇿": "flag: Czechia",
	"🇨🇮": "flag: Côte d'Ivoire",
	"🇩🇰": "flag: Denmark",
	"🇩🇬": "flag: Diego Garcia",
	"🇩🇯": "flag: Djibouti",
	"🇩🇲": "flag: Dominica",
	"🇩🇴": "flag: Dominican Republic",
	"🇪🇨": "flag: Ecuador",
	"🇪🇬": "flag: Egypt",
	"🇸🇻": "flag: El Salvador",
	"🇬🇶": "flag: Equatorial Guinea",
	"🇪🇷": "flag: Eritrea",
	"🇪🇪": "flag: Estonia",
	"🇸🇿": "flag: Eswatini",
	"🇪🇹": "flag: Ethiopia",
	"🇪🇺": "flag: European Union",
	"🇫🇰": "flag: Falkland Islands",
	"🇫🇴": "flag: Faroe Islands",
	"🇫🇯": "flag: Fiji",
	"🇫🇮": "flag: Finland",
	"🇫🇷": "flag: France",
	"🇬🇫": "flag: French Guiana",
	"🇵🇫": "flag: French Polynesia",
	"🇹🇫": "flag: French Southern Territories",
	"🇬🇦": "flag: Gabon",
	"🇬🇲": "flag: Gambia",
	"🇬🇪": "flag: Georgia",
	"🇩🇪": "flag: Germany",
	"🇬🇭": "flag: Ghana",
	"🇬🇮": "flag: Gibraltar",
	"🇬🇷": "flag: Greece",
	"🇬🇱": "flag: Greenland",
	"🇬🇩": "flag: Grenada",
	"🇬🇵": "flag: Guadeloupe",
	"🇬🇺": "flag: Guam",
	"🇬🇹": "flag: Guatemala",
	"🇬🇬": "flag: Guernsey",
	"🇬🇳": "flag: Guinea",
	"🇬🇼": "flag: Guinea-Bissau",
	"🇬🇾": "flag: Guyana",
	"🇭🇹": "flag: Haiti",
	"🇭🇲": "flag: Heard & McDonald Islands",
	"🇭🇳": "flag: Honduras",
	"🇭🇰": "flag: Hong Kong SAR China",
	"🇭🇺": "flag: Hungary",
	"🇮🇸": "flag: Iceland",
	"🇮🇳": "flag: India",
	"🇮🇩": "flag: Indonesia",
	"🇮🇷": "flag: Iran",
	"🇮🇶": "flag: Iraq",
	"🇮🇪": "flag: Ireland",
	"🇮🇲": "flag: Isle of Man",
	"🇮🇱": "flag: Israel",
	"🇮🇹": "flag: Italy",
	"🇯🇲": "flag: Jamaica",
	"🇯🇵": "flag: Japan",
	"🇯🇪": "flag: Jersey",
	"🇯🇴": "flag: Jordan",
	"🇰🇿": "flag: Kazakhstan",
	"🇰🇪": "flag: Kenya",
	"🇰🇮": "flag: Kiribati",
	"🇽🇰": "flag: Kosovo",
	"🇰🇼": "flag: Kuwait",
	"🇰🇬": "flag: Kyrgyzstan",
	"🇱🇦": "flag: Laos",
	"🇱🇻": "flag: Latvia",
	"🇱🇧": "flag: Lebanon",
	"🇱🇸": "flag: Lesotho",
	"🇱🇷": "flag: Liberia",
	"🇱🇾": "flag: Libya",
	"🇱🇮": "flag: Liechtenstein",
	"🇱🇹": "flag: Lithuania",
	"🇱🇺": "flag: Luxembourg",
	"🇲🇴": "flag: Macao SAR China",
	"🇲🇬": "flag: Madagascar",
	"🇲🇼": "flag: Malawi",
	"🇲🇾": "flag: Malaysia",
	"🇲🇻": "flag: Maldives",
	"🇲🇱": "flag: Mali",
	"🇲🇹": "flag: Malta",
	"🇲🇭": "flag: Marshall Islands",
	"🇲🇶": "flag: Martinique",
	"🇲🇷": "flag: Mauritania",
	"🇲🇺": "flag: Mauritius",
	"🇾🇹": "flag: Mayotte",
	"🇲🇽": "flag: Mexico",
	"🇫🇲": "flag: Micronesia",
	"🇲🇩": "flag: Moldova",
	"🇲🇨": "flag: Monaco",
	"🇲🇳": "flag: Mongolia",
	"🇲🇪": "flag: Montenegro",
	"🇲🇸": "flag: Montserrat",
	"🇲🇦": "flag: Morocco",
	"🇲🇿": "flag: Mozambique",
	"🇲🇲": "flag: Myanmar (Burma)",
	"🇳🇦": "flag: Namibia",
	"🇳🇷": "flag: Nauru",
	"🇳🇵": "flag: Nepal",
	"🇳🇱": "flag: Netherlands",
	"🇳🇨": "flag: New Caledonia",
	"🇳🇿": "flag: New Zealand",
	"🇳🇮": "flag: Nicaragua",
	"🇳🇪": "flag: Niger",
	"🇳🇬": "flag: Nigeria",
	"🇳🇺": "flag: Niue",
	"🇳🇫": "flag: Norfolk Island",
	"🇰🇵": "flag: North Korea",
	"🇲🇰": "flag: North Macedonia",
	"🇲🇵": "flag: Northern Mariana Islands",
	"🇳🇴": "flag: Norway",
	"🇴🇲": "flag: Oman",
	"🇵🇰": "flag: Pakistan",
	"🇵🇼": "flag: Palau",
	"🇵🇸": "flag: Palestinian Territories",
	"🇵🇦": "flag: Panama",
	"🇵🇬": "flag: Papua New Guinea",
	"🇵🇾": "flag: Paraguay",
	"🇵🇪": "flag: Peru",
	"🇵🇭": "flag: Philippines",
	"🇵🇳": "flag: Pitcairn Islands",
	"🇵🇱": "flag: Poland",
	"🇵🇹": "flag: Portugal",
	"🇵🇷": "flag: Puerto Rico",
	"🇶🇦": "flag: Qatar",
	"🇷🇴": "flag: Romania",
	"🇷🇺": "flag: Russia",
	"🇷🇼": "flag: Rwanda",
	"🇷🇪": "flag: Réunion",
	"🇼🇸": "flag: Samoa",
	"🇸🇲": "flag: San Marino",
	"🇸🇦": "flag: Saudi Arabia",
	"🇸🇳": "flag: Senegal",
	"🇷🇸": "flag: Serbia",
	"🇸🇨": "flag: Seychelles",
	"🇸🇱": "flag: Sierra Leone",
	"🇸🇬": "flag: Singapore",
	"🇸🇽": "flag: Sint Maarten",
	"🇸🇰": "flag: Slovakia",
	"🇸🇮": "flag: Slovenia",
	"🇸🇧": "flag: Solomon Islands",
	"🇸🇴": "flag: Somalia",
	"🇿🇦": "flag: South Africa",
	"🇬🇸": "flag: South Georgia & South Sandwich Islands",
	"🇰🇷": "flag: South Korea",
	"🇸🇸": "flag: South Sudan",
	"🇪🇸": "flag: Spain",
	"🇱🇰": "flag: Sri Lanka",
	"🇧🇱": "flag: St. Barthélemy",
	"🇸🇭": "flag: St. Helena",
	"🇰🇳": "flag: St. Kitts & Nevis",
	"🇱🇨": "flag: St. Lucia",
	"🇲🇫": "flag: St. Martin",
	"🇵🇲": "flag: St. Pierre & Miquelon",
	"🇻🇨": "flag: St. Vincent & Grenadines",
	"🇸🇩": "flag: Sudan",
	"🇸🇷": "flag: Suriname",
	"🇸🇯": "flag: Svalbard & Jan Mayen",
	"🇸🇪": "flag: Sweden",
	"🇨🇭": "flag: Switzerland",
	"🇸🇾": "flag: Syria",
	"🇸🇹": "flag: São Tomé & Príncipe",
	"🇹🇼": "flag: Taiwan",
	"🇹🇯": "flag: Tajikistan",
	"🇹🇿": "flag: Tanzania",
	"🇹🇭": "flag: Thailand",
	"🇹🇱": "flag: Timor-Leste",
	"🇹🇬": "flag: Togo",
	"🇹🇰": "flag: Tokelau",
	"🇹🇴": "flag: Tonga",
	"🇹🇹": "flag: Trinidad & Tobago",
	"🇹🇦": "flag: Tristan da Cunha",
	"🇹🇳": "flag: Tunisia",
	"🇹🇲": "flag: Turkmenistan",
	"🇹🇨": "flag: Turks & Caicos Islands",
	"🇹🇻": "flag: Tuvalu",
	"🇹🇷": "flag: Türkiye",
	"🇺🇲": "flag: U.S. Outlying Islands",
	"🇻🇮": "flag: U.S. Virgin Islands",
	"🇺🇬": "flag: Uganda",
	"🇺🇦": "flag: Ukraine",
	"🇦🇪": "flag: United Arab Emirates",
	"🇬🇧": "flag: United Kingdom",
	"🇺🇳": "flag: United Nations",
	"🇺🇸": "flag: United States",
	"🇺🇾": "flag: Uruguay",
	"🇺🇿": "flag: Uzbekistan",
	"🇻🇺": "flag: Vanuatu",
	"🇻🇦": "flag: Vatican City",
	"🇻🇪": "flag: Venezuela",
	"🇻🇳": "flag: Vietnam",
	"🇼🇫": "flag: Wallis & Futuna",
	"🇪🇭": "flag: Western Sahara",
	"🇾🇪": "flag: Yemen",
	"🇿🇲": "flag: Zambia",
	"🇿🇼": "flag: Zimbabwe",
	"🇦🇽": "flag: Åland Islands",
	"🦩": "flamingo",
	"🔦": "flashlight",
	"🥿": "flat shoe",
	"🫓": "flatbread",
	"⚜️": "fleur-de-lis",
	"💪": "flexed biceps",
	"💪🏿": "flexed biceps: dark skin tone",
	"💪🏻": "flexed biceps: light skin tone",
	"💪🏽": "flexed biceps: medium skin tone",
	"💪🏾": "flexed biceps: medium-dark skin tone",
	"💪🏼": "flexed biceps: medium-light skin tone",
	"💾": "floppy disk",
	"🎴": "flower playing cards",
	"😳": "flushed face",
	"🪈": "flute",
	"🪰": "fly",
	"🥏": "flying disc",
	"🛸": "flying saucer",
	"🌫️": "fog",
	"🌁": "foggy",
	"🙏": "folded hands",
	"🙏🏿": "folded hands: dark skin tone",
	"🙏🏻": "folded hands: light skin tone",
	"🙏🏽": "folded hands: medium skin tone",
	"🙏🏾": "folded hands: medium-dark skin tone",
	"🙏🏼": "folded hands: medium-light skin tone",
	"🪭": "folding hand fan",
	"🫕": "fondue",
	"🦶": "foot",
	"🦶🏿": "foot: dark skin tone",
	"🦶🏻": "foot: light skin tone",
	"🦶🏽": "foot: medium skin tone",
	"🦶🏾": "foot: medium-dark skin tone",
	"🦶🏼": "foot: medium-light skin tone",
	"👣": "footprints",
	"🍴": "fork and knife",
	"🍽️": "fork and knife with plate",
	"🥠": "fortune cookie",
	"⛲": "fountain",
	"🖋️": "fountain pen",
	"🍀": "four leaf clover",
	"🕓": "four o'clock",
	"🕟": "four-thirty",
	"🦊": "fox",
	"🖼️": "framed picture",
	"🍟": "french fries",
	"🍤": "fried shrimp",
	"🐸": "frog",
	"🐥": "front-facing baby chick",
	"☹️": "frowning face",
	"😦": "frowning face with open mouth",
	"⛽": "fuel pump",
	"🌕": "full moon",
	"🌝": "full moon face",
	"⚱️": "funeral urn",
	"🎲": "game die",
	"🧄": "garlic",
	"⚙️": "gear",
	"💎": "gem stone",
	"🧞": "genie",
	"👻": "ghost",
	"🫚": "ginger root",
	"🦒": "giraffe",
	"👧": "girl",
	"👧🏿": "girl: dark skin tone",
	"👧🏻": "girl: light skin tone",
	"👧🏽": "girl: medium skin tone",
	"👧🏾": "girl: medium-dark skin tone",
	"👧🏼": "girl: medium-light skin tone",
	"🥛": "glass of milk",
	"👓": "glasses",
	"🌎": "globe showing Americas",
	"🌏": "globe showing Asia-Australia",
	"🌍": "globe showing Europe-Africa",
	"🌐": "globe with meridians",
	"🧤": "gloves",
	"🌟": "glowing star",
	"🥅": "goal net",
	"🐐": "goat",
	"👺": "goblin",
	"🥽": "goggles",
	"🪿": "goose",
	"🦍": "gorilla",
	"🎓": "graduation cap",
	"🍇": "grapes",
	"🍏": "green apple",
	"📗": "green book",
	"🟢": "green circle",
	"💚": "green heart",
	"🥗": "green salad",
	"🟩": "green square",
	"🩶": "grey heart",
	"😬": "grimacing face",
	"😺": "grinning cat",
	"😸": "grinning cat with smiling eyes",
	"😀": "grinning face",
	"😃": "grinning face with big eyes",
	"😄": "grinning face with smiling eyes",
	"😅": "grinning face with sweat",
	"😆": "grinning squinting face",
	"💗": "growing heart",
	"💂": "guard",
	"💂🏿": "guard: dark skin tone",
	"💂🏻": "guard: light skin tone",
	"💂🏽": "guard: medium skin tone",
	"💂🏾": "guard: medium-dark skin tone",
	"💂🏼": "guard: medium-light skin tone",
	"🦮": "guide dog",
	"🎸": "guitar",
	"🪮": "hair pick",
	"🍔": "hamburger",
	"🔨": "hammer",
	"⚒️": "hammer and pick",
	"🛠️": "hammer and wrench",
	"🪬": "hamsa",
	"🐹": "hamster",
	"🖐️": "hand with fingers splayed",
	"🖐🏿": "hand with fingers splayed: dark skin tone",
	"🖐🏻": "hand with fingers splayed: light skin tone",
	"🖐🏽": "hand with fingers splayed: medium skin tone",
	"🖐🏾": "hand with fingers splayed: medium-dark skin tone",
	"🖐🏼": "hand with fingers splayed: medium-light skin tone",
	"🫰": "hand with index finger and thumb crossed",
	"🫰🏿": "hand with index finger and thumb crossed: dark skin tone",
	"🫰🏻": "hand with index finger and thumb crossed: light skin tone",
	"🫰🏽": "hand with index finger and thumb crossed: medium skin tone",
	"🫰🏾": "hand with index finger and thumb crossed: medium-dark skin tone",
	"🫰🏼": "hand with index finger and thumb crossed: medium-light skin tone",
	"👜": "handbag",
	"🤝": "handshake",
	"🤝🏿": "handshake: dark skin tone",
	"🤝🏻": "handshake: light skin tone",
	"🤝🏽": "handshake: medium skin tone",
	"🤝🏾": "handshake: medium-dark skin tone",
	"🤝🏼": "handshake: medium-light skin tone",
	"🐣": "hatching chick",
	"🎧": "headphone",
	"🪦": "headstone",
	"🙉": "hear-no-evil monkey",
	"💟": "heart decoration",
	"❣️": "heart exclamation",
	"🫶": "heart hands",
	"🫶🏿": "heart hands: dark skin tone",
	"🫶🏻": "heart hands: light skin tone",
	"🫶🏽": "heart hands: medium skin tone",
	"🫶🏾": "heart hands: medium-dark skin tone",
	"🫶🏼": "heart hands: medium-light skin tone",
	"♥️": "heart suit",
	"💘": "heart with arrow",
	"💝": "heart with ribbon",
	"💲": "heavy dollar sign",
	"🟰": "heavy equals sign",
	"🦔": "hedgehog",
	"🚁": "helicopter",
	"🌿": "herb",
	"🌺": "hibiscus",
	"⚡": "high voltage",
	"👠": "high-heeled shoe",
	"🚄": "high-speed train",
	"🥾": "hiking boot",
	"🛕": "hindu temple",
	"🦛": "hippopotamus",
	"🕳️": "hole",
	"⭕": "hollow red circle",
	"🍯": "honey pot",
	"🐝": "honeybee",
	"🪝": "hook",
	"🚥": "horizontal traffic light",
	"🐎": "horse",
	"🐴": "horse face",
	"🏇": "horse racing",
	"🏇🏿": "horse racing: dark skin tone",
	"🏇🏻": "horse racing: light skin tone",
	"🏇🏽": "horse racing: medium skin tone",
	"🏇🏾": "horse racing: medium-dark skin tone",
	"🏇🏼": "horse racing: medium-light skin tone",
	"🏥": "hospital",
	"☕": "hot beverage",
	"🌭": "hot dog",
	"🥵": "hot face",
	"🌶️": "hot pepper",
	"♨️": "hot springs",
	"🏨": "hotel",
	"⌛": "hourglass done",
	"⏳": "hourglass not done",
	"🏠": "house",
	"🏡": "house with garden",
	"🏘️": "houses",
	"💯": "hundred points",
	"😯": "hushed face",
	"🛖": "hut",
	"🪻": "hyacinth",
	"🧊": "ice",
	"🍨": "ice cream",
	"🏒": "ice hockey",
	"⛸️": "ice skate",
	"🪪": "identification card",
	"📥": "inbox tray",
	"📨": "incoming envelope",
	"🫵": "index pointing at the viewer",
	"🫵🏿": "index pointing at the viewer: dark skin tone",
	"🫵🏻": "index pointing at the viewer: light skin tone",
	"🫵🏽": "index pointing at the viewer: medium skin tone",
	"🫵🏾": "index pointing at the viewer: medium-dark skin tone",
	"🫵🏼": "index pointing at the viewer: medium-light skin tone",
	"☝️": "index pointing up",
	"☝🏿": "index pointing up: dark skin tone",
	"☝🏻": "index pointing up: light skin tone",
	"☝🏽": "index pointing up: medium skin tone",
	"☝🏾": "index pointing up: medium-dark skin tone",
	"☝🏼": "index pointing up: medium-light skin tone",
	"♾️": "infinity",
	ℹ️: "information",
	"🔤": "input latin letters",
	"🔡": "input latin lowercase",
	"🔠": "input latin uppercase",
	"🔢": "input numbers",
	"🔣": "input symbols",
	"🎃": "jack-o-lantern",
	"🫙": "jar",
	"👖": "jeans",
	"🪼": "jellyfish",
	"🃏": "joker",
	"🕹️": "joystick",
	"🕋": "kaaba",
	"🦘": "kangaroo",
	"🔑": "key",
	"⌨️": "keyboard",
	"#️⃣": "keycap: #",
	"*️⃣": "keycap: *",
	"0️⃣": "keycap: 0",
	"1️⃣": "keycap: 1",
	"🔟": "keycap: 10",
	"2️⃣": "keycap: 2",
	"3️⃣": "keycap: 3",
	"4️⃣": "keycap: 4",
	"5️⃣": "keycap: 5",
	"6️⃣": "keycap: 6",
	"7️⃣": "keycap: 7",
	"8️⃣": "keycap: 8",
	"9️⃣": "keycap: 9",
	"🪯": "khanda",
	"🛴": "kick scooter",
	"👘": "kimono",
	"💏": "kiss",
	"💋": "kiss mark",
	"💏🏿": "kiss: dark skin tone",
	"💏🏻": "kiss: light skin tone",
	"💏🏽": "kiss: medium skin tone",
	"💏🏾": "kiss: medium-dark skin tone",
	"💏🏼": "kiss: medium-light skin tone",
	"😽": "kissing cat",
	"😗": "kissing face",
	"😚": "kissing face with closed eyes",
	"😙": "kissing face with smiling eyes",
	"🔪": "kitchen knife",
	"🪁": "kite",
	"🥝": "kiwi fruit",
	"🪢": "knot",
	"🐨": "koala",
	"🥼": "lab coat",
	"🏷️": "label",
	"🥍": "lacrosse",
	"🪜": "ladder",
	"🐞": "lady beetle",
	"💻": "laptop",
	"🔷": "large blue diamond",
	"🔶": "large orange diamond",
	"🌗": "last quarter moon",
	"🌜": "last quarter moon face",
	"⏮️": "last track button",
	"✝️": "latin cross",
	"🍃": "leaf fluttering in wind",
	"🥬": "leafy green",
	"📒": "ledger",
	"⬅️": "left arrow",
	"↪️": "left arrow curving right",
	"🛅": "left luggage",
	"🗨️": "left speech bubble",
	"🤛": "left-facing fist",
	"🤛🏿": "left-facing fist: dark skin tone",
	"🤛🏻": "left-facing fist: light skin tone",
	"🤛🏽": "left-facing fist: medium skin tone",
	"🤛🏾": "left-facing fist: medium-dark skin tone",
	"🤛🏼": "left-facing fist: medium-light skin tone",
	"↔️": "left-right arrow",
	"🫲": "leftwards hand",
	"🫲🏿": "leftwards hand: dark skin tone",
	"🫲🏻": "leftwards hand: light skin tone",
	"🫲🏽": "leftwards hand: medium skin tone",
	"🫲🏾": "leftwards hand: medium-dark skin tone",
	"🫲🏼": "leftwards hand: medium-light skin tone",
	"🫷": "leftwards pushing hand",
	"🫷🏿": "leftwards pushing hand: dark skin tone",
	"🫷🏻": "leftwards pushing hand: light skin tone",
	"🫷🏽": "leftwards pushing hand: medium skin tone",
	"🫷🏾": "leftwards pushing hand: medium-dark skin tone",
	"🫷🏼": "leftwards pushing hand: medium-light skin tone",
	"🦵": "leg",
	"🦵🏿": "leg: dark skin tone",
	"🦵🏻": "leg: light skin tone",
	"🦵🏽": "leg: medium skin tone",
	"🦵🏾": "leg: medium-dark skin tone",
	"🦵🏼": "leg: medium-light skin tone",
	"🍋": "lemon",
	"🐆": "leopard",
	"🎚️": "level slider",
	"🩵": "light blue heart",
	"💡": "light bulb",
	"🚈": "light rail",
	"🔗": "link",
	"🖇️": "linked paperclips",
	"🦁": "lion",
	"💄": "lipstick",
	"🚮": "litter in bin sign",
	"🦎": "lizard",
	"🦙": "llama",
	"🦞": "lobster",
	"🔒": "locked",
	"🔐": "locked with key",
	"🔏": "locked with pen",
	"🚂": "locomotive",
	"🍭": "lollipop",
	"🪘": "long drum",
	"🧴": "lotion bottle",
	"🪷": "lotus",
	"😭": "loudly crying face",
	"📢": "loudspeaker",
	"🏩": "love hotel",
	"💌": "love letter",
	"🤟": "love-you gesture",
	"🤟🏿": "love-you gesture: dark skin tone",
	"🤟🏻": "love-you gesture: light skin tone",
	"🤟🏽": "love-you gesture: medium skin tone",
	"🤟🏾": "love-you gesture: medium-dark skin tone",
	"🤟🏼": "love-you gesture: medium-light skin tone",
	"🪫": "low battery",
	"🧳": "luggage",
	"🫁": "lungs",
	"🤥": "lying face",
	"🧙": "mage",
	"🧙🏿": "mage: dark skin tone",
	"🧙🏻": "mage: light skin tone",
	"🧙🏽": "mage: medium skin tone",
	"🧙🏾": "mage: medium-dark skin tone",
	"🧙🏼": "mage: medium-light skin tone",
	"🪄": "magic wand",
	"🧲": "magnet",
	"🔍": "magnifying glass tilted left",
	"🔎": "magnifying glass tilted right",
	"🀄": "mahjong red dragon",
	"♂️": "male sign",
	"🦣": "mammoth",
	"👨": "man",
	"🕺": "man dancing",
	"🕺🏿": "man dancing: dark skin tone",
	"🕺🏻": "man dancing: light skin tone",
	"🕺🏽": "man dancing: medium skin tone",
	"🕺🏾": "man dancing: medium-dark skin tone",
	"🕺🏼": "man dancing: medium-light skin tone",
	"👞": "man's shoe",
	"👨🏿": "man: dark skin tone",
	"👨🏻": "man: light skin tone",
	"👨🏽": "man: medium skin tone",
	"👨🏾": "man: medium-dark skin tone",
	"👨🏼": "man: medium-light skin tone",
	"🥭": "mango",
	"🕰️": "mantelpiece clock",
	"🦽": "manual wheelchair",
	"🗾": "map of Japan",
	"🍁": "maple leaf",
	"🪇": "maracas",
	"🥋": "martial arts uniform",
	"🧉": "mate",
	"🍖": "meat on bone",
	"🦾": "mechanical arm",
	"🦿": "mechanical leg",
	"⚕️": "medical symbol",
	"📣": "megaphone",
	"🍈": "melon",
	"🫠": "melting face",
	"📝": "memo",
	"👬": "men holding hands",
	"👬🏿": "men holding hands: dark skin tone",
	"👬🏻": "men holding hands: light skin tone",
	"👬🏽": "men holding hands: medium skin tone",
	"👬🏾": "men holding hands: medium-dark skin tone",
	"👬🏼": "men holding hands: medium-light skin tone",
	"🚹": "men's room",
	"🕎": "menorah",
	"🧜": "merperson",
	"🧜🏿": "merperson: dark skin tone",
	"🧜🏻": "merperson: light skin tone",
	"🧜🏽": "merperson: medium skin tone",
	"🧜🏾": "merperson: medium-dark skin tone",
	"🧜🏼": "merperson: medium-light skin tone",
	"🚇": "metro",
	"🦠": "microbe",
	"🎤": "microphone",
	"🔬": "microscope",
	"🖕": "middle finger",
	"🖕🏿": "middle finger: dark skin tone",
	"🖕🏻": "middle finger: light skin tone",
	"🖕🏽": "middle finger: medium skin tone",
	"🖕🏾": "middle finger: medium-dark skin tone",
	"🖕🏼": "middle finger: medium-light skin tone",
	"🪖": "military helmet",
	"🎖️": "military medal",
	"🌌": "milky way",
	"🚐": "minibus",
	"➖": "minus",
	"🪞": "mirror",
	"🪩": "mirror ball",
	"🗿": "moai",
	"📱": "mobile phone",
	"📴": "mobile phone off",
	"📲": "mobile phone with arrow",
	"💰": "money bag",
	"💸": "money with wings",
	"🤑": "money-mouth face",
	"🐒": "monkey",
	"🐵": "monkey face",
	"🚝": "monorail",
	"🥮": "moon cake",
	"🎑": "moon viewing ceremony",
	"🫎": "moose",
	"🕌": "mosque",
	"🦟": "mosquito",
	"🛥️": "motor boat",
	"🛵": "motor scooter",
	"🏍️": "motorcycle",
	"🦼": "motorized wheelchair",
	"🛣️": "motorway",
	"🗻": "mount fuji",
	"⛰️": "mountain",
	"🚠": "mountain cableway",
	"🚞": "mountain railway",
	"🐁": "mouse",
	"🐭": "mouse face",
	"🪤": "mouse trap",
	"👄": "mouth",
	"🎥": "movie camera",
	"✖️": "multiply",
	"🍄": "mushroom",
	"🎹": "musical keyboard",
	"🎵": "musical note",
	"🎶": "musical notes",
	"🎼": "musical score",
	"🔇": "muted speaker",
	"💅": "nail polish",
	"💅🏿": "nail polish: dark skin tone",
	"💅🏻": "nail polish: light skin tone",
	"💅🏽": "nail polish: medium skin tone",
	"💅🏾": "nail polish: medium-dark skin tone",
	"💅🏼": "nail polish: medium-light skin tone",
	"📛": "name badge",
	"🏞️": "national park",
	"🤢": "nauseated face",
	"🧿": "nazar amulet",
	"👔": "necktie",
	"🤓": "nerd face",
	"🪺": "nest with eggs",
	"🪆": "nesting dolls",
	"😐": "neutral face",
	"🌑": "new moon",
	"🌚": "new moon face",
	"📰": "newspaper",
	"⏭️": "next track button",
	"🌃": "night with stars",
	"🕘": "nine o'clock",
	"🕤": "nine-thirty",
	"🥷": "ninja",
	"🥷🏿": "ninja: dark skin tone",
	"🥷🏻": "ninja: light skin tone",
	"🥷🏽": "ninja: medium skin tone",
	"🥷🏾": "ninja: medium-dark skin tone",
	"🥷🏼": "ninja: medium-light skin tone",
	"🚳": "no bicycles",
	"⛔": "no entry",
	"🚯": "no littering",
	"📵": "no mobile phones",
	"🔞": "no one under eighteen",
	"🚷": "no pedestrians",
	"🚭": "no smoking",
	"🚱": "non-potable water",
	"👃": "nose",
	"👃🏿": "nose: dark skin tone",
	"👃🏻": "nose: light skin tone",
	"👃🏽": "nose: medium skin tone",
	"👃🏾": "nose: medium-dark skin tone",
	"👃🏼": "nose: medium-light skin tone",
	"📓": "notebook",
	"📔": "notebook with decorative cover",
	"🔩": "nut and bolt",
	"🐙": "octopus",
	"🍢": "oden",
	"🏢": "office building",
	"👹": "ogre",
	"🛢️": "oil drum",
	"🗝️": "old key",
	"👴": "old man",
	"👴🏿": "old man: dark skin tone",
	"👴🏻": "old man: light skin tone",
	"👴🏽": "old man: medium skin tone",
	"👴🏾": "old man: medium-dark skin tone",
	"👴🏼": "old man: medium-light skin tone",
	"👵": "old woman",
	"👵🏿": "old woman: dark skin tone",
	"👵🏻": "old woman: light skin tone",
	"👵🏽": "old woman: medium skin tone",
	"👵🏾": "old woman: medium-dark skin tone",
	"👵🏼": "old woman: medium-light skin tone",
	"🧓": "older person",
	"🧓🏿": "older person: dark skin tone",
	"🧓🏻": "older person: light skin tone",
	"🧓🏽": "older person: medium skin tone",
	"🧓🏾": "older person: medium-dark skin tone",
	"🧓🏼": "older person: medium-light skin tone",
	"🫒": "olive",
	"🕉️": "om",
	"🚘": "oncoming automobile",
	"🚍": "oncoming bus",
	"👊": "oncoming fist",
	"👊🏿": "oncoming fist: dark skin tone",
	"👊🏻": "oncoming fist: light skin tone",
	"👊🏽": "oncoming fist: medium skin tone",
	"👊🏾": "oncoming fist: medium-dark skin tone",
	"👊🏼": "oncoming fist: medium-light skin tone",
	"🚔": "oncoming police car",
	"🚖": "oncoming taxi",
	"🕐": "one o'clock",
	"🩱": "one-piece swimsuit",
	"🕜": "one-thirty",
	"🧅": "onion",
	"📖": "open book",
	"📂": "open file folder",
	"👐": "open hands",
	"👐🏿": "open hands: dark skin tone",
	"👐🏻": "open hands: light skin tone",
	"👐🏽": "open hands: medium skin tone",
	"👐🏾": "open hands: medium-dark skin tone",
	"👐🏼": "open hands: medium-light skin tone",
	"📭": "open mailbox with lowered flag",
	"📬": "open mailbox with raised flag",
	"💿": "optical disk",
	"📙": "orange book",
	"🟠": "orange circle",
	"🧡": "orange heart",
	"🟧": "orange square",
	"🦧": "orangutan",
	"☦️": "orthodox cross",
	"🦦": "otter",
	"📤": "outbox tray",
	"🦉": "owl",
	"🐂": "ox",
	"🦪": "oyster",
	"📦": "package",
	"📄": "page facing up",
	"📃": "page with curl",
	"📟": "pager",
	"🖌️": "paintbrush",
	"🫳": "palm down hand",
	"🫳🏿": "palm down hand: dark skin tone",
	"🫳🏻": "palm down hand: light skin tone",
	"🫳🏽": "palm down hand: medium skin tone",
	"🫳🏾": "palm down hand: medium-dark skin tone",
	"🫳🏼": "palm down hand: medium-light skin tone",
	"🌴": "palm tree",
	"🫴": "palm up hand",
	"🫴🏿": "palm up hand: dark skin tone",
	"🫴🏻": "palm up hand: light skin tone",
	"🫴🏽": "palm up hand: medium skin tone",
	"🫴🏾": "palm up hand: medium-dark skin tone",
	"🫴🏼": "palm up hand: medium-light skin tone",
	"🤲": "palms up together",
	"🤲🏿": "palms up together: dark skin tone",
	"🤲🏻": "palms up together: light skin tone",
	"🤲🏽": "palms up together: medium skin tone",
	"🤲🏾": "palms up together: medium-dark skin tone",
	"🤲🏼": "palms up together: medium-light skin tone",
	"🥞": "pancakes",
	"🐼": "panda",
	"📎": "paperclip",
	"🪂": "parachute",
	"🦜": "parrot",
	"〽️": "part alternation mark",
	"🎉": "party popper",
	"🥳": "partying face",
	"🛳️": "passenger ship",
	"🛂": "passport control",
	"⏸️": "pause button",
	"🐾": "paw prints",
	"🫛": "pea pod",
	"☮️": "peace symbol",
	"🍑": "peach",
	"🦚": "peacock",
	"🥜": "peanuts",
	"🍐": "pear",
	"🖊️": "pen",
	"✏️": "pencil",
	"🐧": "penguin",
	"😔": "pensive face",
	"🫂": "people hugging",
	"👯": "people with bunny ears",
	"🤼": "people wrestling",
	"🎭": "performing arts",
	"😣": "persevering face",
	"🧑": "person",
	"🚴": "person biking",
	"🚴🏿": "person biking: dark skin tone",
	"🚴🏻": "person biking: light skin tone",
	"🚴🏽": "person biking: medium skin tone",
	"🚴🏾": "person biking: medium-dark skin tone",
	"🚴🏼": "person biking: medium-light skin tone",
	"⛹️": "person bouncing ball",
	"⛹🏿": "person bouncing ball: dark skin tone",
	"⛹🏻": "person bouncing ball: light skin tone",
	"⛹🏽": "person bouncing ball: medium skin tone",
	"⛹🏾": "person bouncing ball: medium-dark skin tone",
	"⛹🏼": "person bouncing ball: medium-light skin tone",
	"🙇": "person bowing",
	"🙇🏿": "person bowing: dark skin tone",
	"🙇🏻": "person bowing: light skin tone",
	"🙇🏽": "person bowing: medium skin tone",
	"🙇🏾": "person bowing: medium-dark skin tone",
	"🙇🏼": "person bowing: medium-light skin tone",
	"🤸": "person cartwheeling",
	"🤸🏿": "person cartwheeling: dark skin tone",
	"🤸🏻": "person cartwheeling: light skin tone",
	"🤸🏽": "person cartwheeling: medium skin tone",
	"🤸🏾": "person cartwheeling: medium-dark skin tone",
	"🤸🏼": "person cartwheeling: medium-light skin tone",
	"🧗": "person climbing",
	"🧗🏿": "person climbing: dark skin tone",
	"🧗🏻": "person climbing: light skin tone",
	"🧗🏽": "person climbing: medium skin tone",
	"🧗🏾": "person climbing: medium-dark skin tone",
	"🧗🏼": "person climbing: medium-light skin tone",
	"🤦": "person facepalming",
	"🤦🏿": "person facepalming: dark skin tone",
	"🤦🏻": "person facepalming: light skin tone",
	"🤦🏽": "person facepalming: medium skin tone",
	"🤦🏾": "person facepalming: medium-dark skin tone",
	"🤦🏼": "person facepalming: medium-light skin tone",
	"🤺": "person fencing",
	"🙍": "person frowning",
	"🙍🏿": "person frowning: dark skin tone",
	"🙍🏻": "person frowning: light skin tone",
	"🙍🏽": "person frowning: medium skin tone",
	"🙍🏾": "person frowning: medium-dark skin tone",
	"🙍🏼": "person frowning: medium-light skin tone",
	"🙅": "person gesturing NO",
	"🙅🏿": "person gesturing NO: dark skin tone",
	"🙅🏻": "person gesturing NO: light skin tone",
	"🙅🏽": "person gesturing NO: medium skin tone",
	"🙅🏾": "person gesturing NO: medium-dark skin tone",
	"🙅🏼": "person gesturing NO: medium-light skin tone",
	"🙆": "person gesturing OK",
	"🙆🏿": "person gesturing OK: dark skin tone",
	"🙆🏻": "person gesturing OK: light skin tone",
	"🙆🏽": "person gesturing OK: medium skin tone",
	"🙆🏾": "person gesturing OK: medium-dark skin tone",
	"🙆🏼": "person gesturing OK: medium-light skin tone",
	"💇": "person getting haircut",
	"💇🏿": "person getting haircut: dark skin tone",
	"💇🏻": "person getting haircut: light skin tone",
	"💇🏽": "person getting haircut: medium skin tone",
	"💇🏾": "person getting haircut: medium-dark skin tone",
	"💇🏼": "person getting haircut: medium-light skin tone",
	"💆": "person getting massage",
	"💆🏿": "person getting massage: dark skin tone",
	"💆🏻": "person getting massage: light skin tone",
	"💆🏽": "person getting massage: medium skin tone",
	"💆🏾": "person getting massage: medium-dark skin tone",
	"💆🏼": "person getting massage: medium-light skin tone",
	"🏌️": "person golfing",
	"🏌🏿": "person golfing: dark skin tone",
	"🏌🏻": "person golfing: light skin tone",
	"🏌🏽": "person golfing: medium skin tone",
	"🏌🏾": "person golfing: medium-dark skin tone",
	"🏌🏼": "person golfing: medium-light skin tone",
	"🛌": "person in bed",
	"🛌🏿": "person in bed: dark skin tone",
	"🛌🏻": "person in bed: light skin tone",
	"🛌🏽": "person in bed: medium skin tone",
	"🛌🏾": "person in bed: medium-dark skin tone",
	"🛌🏼": "person in bed: medium-light skin tone",
	"🧘": "person in lotus position",
	"🧘🏿": "person in lotus position: dark skin tone",
	"🧘🏻": "person in lotus position: light skin tone",
	"🧘🏽": "person in lotus position: medium skin tone",
	"🧘🏾": "person in lotus position: medium-dark skin tone",
	"🧘🏼": "person in lotus position: medium-light skin tone",
	"🧖": "person in steamy room",
	"🧖🏿": "person in steamy room: dark skin tone",
	"🧖🏻": "person in steamy room: light skin tone",
	"🧖🏽": "person in steamy room: medium skin tone",
	"🧖🏾": "person in steamy room: medium-dark skin tone",
	"🧖🏼": "person in steamy room: medium-light skin tone",
	"🕴️": "person in suit levitating",
	"🕴🏿": "person in suit levitating: dark skin tone",
	"🕴🏻": "person in suit levitating: light skin tone",
	"🕴🏽": "person in suit levitating: medium skin tone",
	"🕴🏾": "person in suit levitating: medium-dark skin tone",
	"🕴🏼": "person in suit levitating: medium-light skin tone",
	"🤵": "person in tuxedo",
	"🤵🏿": "person in tuxedo: dark skin tone",
	"🤵🏻": "person in tuxedo: light skin tone",
	"🤵🏽": "person in tuxedo: medium skin tone",
	"🤵🏾": "person in tuxedo: medium-dark skin tone",
	"🤵🏼": "person in tuxedo: medium-light skin tone",
	"🤹": "person juggling",
	"🤹🏿": "person juggling: dark skin tone",
	"🤹🏻": "person juggling: light skin tone",
	"🤹🏽": "person juggling: medium skin tone",
	"🤹🏾": "person juggling: medium-dark skin tone",
	"🤹🏼": "person juggling: medium-light skin tone",
	"🧎": "person kneeling",
	"🧎🏿": "person kneeling: dark skin tone",
	"🧎🏻": "person kneeling: light skin tone",
	"🧎🏽": "person kneeling: medium skin tone",
	"🧎🏾": "person kneeling: medium-dark skin tone",
	"🧎🏼": "person kneeling: medium-light skin tone",
	"🏋️": "person lifting weights",
	"🏋🏿": "person lifting weights: dark skin tone",
	"🏋🏻": "person lifting weights: light skin tone",
	"🏋🏽": "person lifting weights: medium skin tone",
	"🏋🏾": "person lifting weights: medium-dark skin tone",
	"🏋🏼": "person lifting weights: medium-light skin tone",
	"🚵": "person mountain biking",
	"🚵🏿": "person mountain biking: dark skin tone",
	"🚵🏻": "person mountain biking: light skin tone",
	"🚵🏽": "person mountain biking: medium skin tone",
	"🚵🏾": "person mountain biking: medium-dark skin tone",
	"🚵🏼": "person mountain biking: medium-light skin tone",
	"🤾": "person playing handball",
	"🤾🏿": "person playing handball: dark skin tone",
	"🤾🏻": "person playing handball: light skin tone",
	"🤾🏽": "person playing handball: medium skin tone",
	"🤾🏾": "person playing handball: medium-dark skin tone",
	"🤾🏼": "person playing handball: medium-light skin tone",
	"🤽": "person playing water polo",
	"🤽🏿": "person playing water polo: dark skin tone",
	"🤽🏻": "person playing water polo: light skin tone",
	"🤽🏽": "person playing water polo: medium skin tone",
	"🤽🏾": "person playing water polo: medium-dark skin tone",
	"🤽🏼": "person playing water polo: medium-light skin tone",
	"🙎": "person pouting",
	"🙎🏿": "person pouting: dark skin tone",
	"🙎🏻": "person pouting: light skin tone",
	"🙎🏽": "person pouting: medium skin tone",
	"🙎🏾": "person pouting: medium-dark skin tone",
	"🙎🏼": "person pouting: medium-light skin tone",
	"🙋": "person raising hand",
	"🙋🏿": "person raising hand: dark skin tone",
	"🙋🏻": "person raising hand: light skin tone",
	"🙋🏽": "person raising hand: medium skin tone",
	"🙋🏾": "person raising hand: medium-dark skin tone",
	"🙋🏼": "person raising hand: medium-light skin tone",
	"🚣": "person rowing boat",
	"🚣🏿": "person rowing boat: dark skin tone",
	"🚣🏻": "person rowing boat: light skin tone",
	"🚣🏽": "person rowing boat: medium skin tone",
	"🚣🏾": "person rowing boat: medium-dark skin tone",
	"🚣🏼": "person rowing boat: medium-light skin tone",
	"🏃": "person running",
	"🏃🏿": "person running: dark skin tone",
	"🏃🏻": "person running: light skin tone",
	"🏃🏽": "person running: medium skin tone",
	"🏃🏾": "person running: medium-dark skin tone",
	"🏃🏼": "person running: medium-light skin tone",
	"🤷": "person shrugging",
	"🤷🏿": "person shrugging: dark skin tone",
	"🤷🏻": "person shrugging: light skin tone",
	"🤷🏽": "person shrugging: medium skin tone",
	"🤷🏾": "person shrugging: medium-dark skin tone",
	"🤷🏼": "person shrugging: medium-light skin tone",
	"🧍": "person standing",
	"🧍🏿": "person standing: dark skin tone",
	"🧍🏻": "person standing: light skin tone",
	"🧍🏽": "person standing: medium skin tone",
	"🧍🏾": "person standing: medium-dark skin tone",
	"🧍🏼": "person standing: medium-light skin tone",
	"🏄": "person surfing",
	"🏄🏿": "person surfing: dark skin tone",
	"🏄🏻": "person surfing: light skin tone",
	"🏄🏽": "person surfing: medium skin tone",
	"🏄🏾": "person surfing: medium-dark skin tone",
	"🏄🏼": "person surfing: medium-light skin tone",
	"🏊": "person swimming",
	"🏊🏿": "person swimming: dark skin tone",
	"🏊🏻": "person swimming: light skin tone",
	"🏊🏽": "person swimming: medium skin tone",
	"🏊🏾": "person swimming: medium-dark skin tone",
	"🏊🏼": "person swimming: medium-light skin tone",
	"🛀": "person taking bath",
	"🛀🏿": "person taking bath: dark skin tone",
	"🛀🏻": "person taking bath: light skin tone",
	"🛀🏽": "person taking bath: medium skin tone",
	"🛀🏾": "person taking bath: medium-dark skin tone",
	"🛀🏼": "person taking bath: medium-light skin tone",
	"💁": "person tipping hand",
	"💁🏿": "person tipping hand: dark skin tone",
	"💁🏻": "person tipping hand: light skin tone",
	"💁🏽": "person tipping hand: medium skin tone",
	"💁🏾": "person tipping hand: medium-dark skin tone",
	"💁🏼": "person tipping hand: medium-light skin tone",
	"🚶": "person walking",
	"🚶🏿": "person walking: dark skin tone",
	"🚶🏻": "person walking: light skin tone",
	"🚶🏽": "person walking: medium skin tone",
	"🚶🏾": "person walking: medium-dark skin tone",
	"🚶🏼": "person walking: medium-light skin tone",
	"👳": "person wearing turban",
	"👳🏿": "person wearing turban: dark skin tone",
	"👳🏻": "person wearing turban: light skin tone",
	"👳🏽": "person wearing turban: medium skin tone",
	"👳🏾": "person wearing turban: medium-dark skin tone",
	"👳🏼": "person wearing turban: medium-light skin tone",
	"🫅": "person with crown",
	"🫅🏿": "person with crown: dark skin tone",
	"🫅🏻": "person with crown: light skin tone",
	"🫅🏽": "person with crown: medium skin tone",
	"🫅🏾": "person with crown: medium-dark skin tone",
	"🫅🏼": "person with crown: medium-light skin tone",
	"👲": "person with skullcap",
	"👲🏿": "person with skullcap: dark skin tone",
	"👲🏻": "person with skullcap: light skin tone",
	"👲🏽": "person with skullcap: medium skin tone",
	"👲🏾": "person with skullcap: medium-dark skin tone",
	"👲🏼": "person with skullcap: medium-light skin tone",
	"👰": "person with veil",
	"👰🏿": "person with veil: dark skin tone",
	"👰🏻": "person with veil: light skin tone",
	"👰🏽": "person with veil: medium skin tone",
	"👰🏾": "person with veil: medium-dark skin tone",
	"👰🏼": "person with veil: medium-light skin tone",
	"🧔": "person: beard",
	"👱": "person: blond hair",
	"🧑🏿": "person: dark skin tone",
	"🧔🏿": "person: dark skin tone, beard",
	"👱🏿": "person: dark skin tone, blond hair",
	"🧑🏻": "person: light skin tone",
	"🧔🏻": "person: light skin tone, beard",
	"👱🏻": "person: light skin tone, blond hair",
	"🧑🏽": "person: medium skin tone",
	"🧔🏽": "person: medium skin tone, beard",
	"👱🏽": "person: medium skin tone, blond hair",
	"🧑🏾": "person: medium-dark skin tone",
	"🧔🏾": "person: medium-dark skin tone, beard",
	"👱🏾": "person: medium-dark skin tone, blond hair",
	"🧑🏼": "person: medium-light skin tone",
	"🧔🏼": "person: medium-light skin tone, beard",
	"👱🏼": "person: medium-light skin tone, blond hair",
	"🧫": "petri dish",
	"⛏️": "pick",
	"🛻": "pickup truck",
	"🥧": "pie",
	"🐖": "pig",
	"🐷": "pig face",
	"🐽": "pig nose",
	"💩": "pile of poo",
	"💊": "pill",
	"🤌": "pinched fingers",
	"🤌🏿": "pinched fingers: dark skin tone",
	"🤌🏻": "pinched fingers: light skin tone",
	"🤌🏽": "pinched fingers: medium skin tone",
	"🤌🏾": "pinched fingers: medium-dark skin tone",
	"🤌🏼": "pinched fingers: medium-light skin tone",
	"🤏": "pinching hand",
	"🤏🏿": "pinching hand: dark skin tone",
	"🤏🏻": "pinching hand: light skin tone",
	"🤏🏽": "pinching hand: medium skin tone",
	"🤏🏾": "pinching hand: medium-dark skin tone",
	"🤏🏼": "pinching hand: medium-light skin tone",
	"🎍": "pine decoration",
	"🍍": "pineapple",
	"🏓": "ping pong",
	"🩷": "pink heart",
	"🍕": "pizza",
	"🪅": "piñata",
	"🪧": "placard",
	"🛐": "place of worship",
	"▶️": "play button",
	"⏯️": "play or pause button",
	"🛝": "playground slide",
	"🥺": "pleading face",
	"🪠": "plunger",
	"➕": "plus",
	"🚓": "police car",
	"🚨": "police car light",
	"👮": "police officer",
	"👮🏿": "police officer: dark skin tone",
	"👮🏻": "police officer: light skin tone",
	"👮🏽": "police officer: medium skin tone",
	"👮🏾": "police officer: medium-dark skin tone",
	"👮🏼": "police officer: medium-light skin tone",
	"🐩": "poodle",
	"🎱": "pool 8 ball",
	"🍿": "popcorn",
	"🏤": "post office",
	"📯": "postal horn",
	"📮": "postbox",
	"🍲": "pot of food",
	"🚰": "potable water",
	"🥔": "potato",
	"🪴": "potted plant",
	"🍗": "poultry leg",
	"💷": "pound banknote",
	"🫗": "pouring liquid",
	"😾": "pouting cat",
	"📿": "prayer beads",
	"🫃": "pregnant man",
	"🫃🏿": "pregnant man: dark skin tone",
	"🫃🏻": "pregnant man: light skin tone",
	"🫃🏽": "pregnant man: medium skin tone",
	"🫃🏾": "pregnant man: medium-dark skin tone",
	"🫃🏼": "pregnant man: medium-light skin tone",
	"🫄": "pregnant person",
	"🫄🏿": "pregnant person: dark skin tone",
	"🫄🏻": "pregnant person: light skin tone",
	"🫄🏽": "pregnant person: medium skin tone",
	"🫄🏾": "pregnant person: medium-dark skin tone",
	"🫄🏼": "pregnant person: medium-light skin tone",
	"🤰": "pregnant woman",
	"🤰🏿": "pregnant woman: dark skin tone",
	"🤰🏻": "pregnant woman: light skin tone",
	"🤰🏽": "pregnant woman: medium skin tone",
	"🤰🏾": "pregnant woman: medium-dark skin tone",
	"🤰🏼": "pregnant woman: medium-light skin tone",
	"🥨": "pretzel",
	"🤴": "prince",
	"🤴🏿": "prince: dark skin tone",
	"🤴🏻": "prince: light skin tone",
	"🤴🏽": "prince: medium skin tone",
	"🤴🏾": "prince: medium-dark skin tone",
	"🤴🏼": "prince: medium-light skin tone",
	"👸": "princess",
	"👸🏿": "princess: dark skin tone",
	"👸🏻": "princess: light skin tone",
	"👸🏽": "princess: medium skin tone",
	"👸🏾": "princess: medium-dark skin tone",
	"👸🏼": "princess: medium-light skin tone",
	"🖨️": "printer",
	"🚫": "prohibited",
	"🟣": "purple circle",
	"💜": "purple heart",
	"🟪": "purple square",
	"👛": "purse",
	"📌": "pushpin",
	"🧩": "puzzle piece",
	"🐇": "rabbit",
	"🐰": "rabbit face",
	"🦝": "raccoon",
	"🏎️": "racing car",
	"📻": "radio",
	"🔘": "radio button",
	"☢️": "radioactive",
	"🚃": "railway car",
	"🛤️": "railway track",
	"🌈": "rainbow",
	"🤚": "raised back of hand",
	"🤚🏿": "raised back of hand: dark skin tone",
	"🤚🏻": "raised back of hand: light skin tone",
	"🤚🏽": "raised back of hand: medium skin tone",
	"🤚🏾": "raised back of hand: medium-dark skin tone",
	"🤚🏼": "raised back of hand: medium-light skin tone",
	"✊": "raised fist",
	"✊🏿": "raised fist: dark skin tone",
	"✊🏻": "raised fist: light skin tone",
	"✊🏽": "raised fist: medium skin tone",
	"✊🏾": "raised fist: medium-dark skin tone",
	"✊🏼": "raised fist: medium-light skin tone",
	"✋": "raised hand",
	"✋🏿": "raised hand: dark skin tone",
	"✋🏻": "raised hand: light skin tone",
	"✋🏽": "raised hand: medium skin tone",
	"✋🏾": "raised hand: medium-dark skin tone",
	"✋🏼": "raised hand: medium-light skin tone",
	"🙌": "raising hands",
	"🙌🏿": "raising hands: dark skin tone",
	"🙌🏻": "raising hands: light skin tone",
	"🙌🏽": "raising hands: medium skin tone",
	"🙌🏾": "raising hands: medium-dark skin tone",
	"🙌🏼": "raising hands: medium-light skin tone",
	"🐏": "ram",
	"🐀": "rat",
	"🪒": "razor",
	"🧾": "receipt",
	"⏺️": "record button",
	"♻️": "recycling symbol",
	"🍎": "red apple",
	"🔴": "red circle",
	"🧧": "red envelope",
	"❗": "red exclamation mark",
	"❤️": "red heart",
	"🏮": "red paper lantern",
	"❓": "red question mark",
	"🟥": "red square",
	"🔻": "red triangle pointed down",
	"🔺": "red triangle pointed up",
	"®️": "registered",
	"😌": "relieved face",
	"🎗️": "reminder ribbon",
	"🔁": "repeat button",
	"🔂": "repeat single button",
	"⛑️": "rescue worker's helmet",
	"🚻": "restroom",
	"◀️": "reverse button",
	"💞": "revolving hearts",
	"🦏": "rhinoceros",
	"🎀": "ribbon",
	"🍙": "rice ball",
	"🍘": "rice cracker",
	"🗯️": "right anger bubble",
	"➡️": "right arrow",
	"⤵️": "right arrow curving down",
	"↩️": "right arrow curving left",
	"⤴️": "right arrow curving up",
	"🤜": "right-facing fist",
	"🤜🏿": "right-facing fist: dark skin tone",
	"🤜🏻": "right-facing fist: light skin tone",
	"🤜🏽": "right-facing fist: medium skin tone",
	"🤜🏾": "right-facing fist: medium-dark skin tone",
	"🤜🏼": "right-facing fist: medium-light skin tone",
	"🫱": "rightwards hand",
	"🫱🏿": "rightwards hand: dark skin tone",
	"🫱🏻": "rightwards hand: light skin tone",
	"🫱🏽": "rightwards hand: medium skin tone",
	"🫱🏾": "rightwards hand: medium-dark skin tone",
	"🫱🏼": "rightwards hand: medium-light skin tone",
	"🫸": "rightwards pushing hand",
	"🫸🏿": "rightwards pushing hand: dark skin tone",
	"🫸🏻": "rightwards pushing hand: light skin tone",
	"🫸🏽": "rightwards pushing hand: medium skin tone",
	"🫸🏾": "rightwards pushing hand: medium-dark skin tone",
	"🫸🏼": "rightwards pushing hand: medium-light skin tone",
	"💍": "ring",
	"🛟": "ring buoy",
	"🪐": "ringed planet",
	"🍠": "roasted sweet potato",
	"🤖": "robot",
	"🪨": "rock",
	"🚀": "rocket",
	"🧻": "roll of paper",
	"🗞️": "rolled-up newspaper",
	"🎢": "roller coaster",
	"🛼": "roller skate",
	"🤣": "rolling on the floor laughing",
	"🐓": "rooster",
	"🌹": "rose",
	"🏵️": "rosette",
	"📍": "round pushpin",
	"🏉": "rugby football",
	"🎽": "running shirt",
	"👟": "running shoe",
	"😥": "sad but relieved face",
	"🧷": "safety pin",
	"🦺": "safety vest",
	"⛵": "sailboat",
	"🍶": "sake",
	"🧂": "salt",
	"🫡": "saluting face",
	"🥪": "sandwich",
	"🥻": "sari",
	"🛰️": "satellite",
	"📡": "satellite antenna",
	"🦕": "sauropod",
	"🎷": "saxophone",
	"🧣": "scarf",
	"🏫": "school",
	"✂️": "scissors",
	"🦂": "scorpion",
	"🪛": "screwdriver",
	"📜": "scroll",
	"🦭": "seal",
	"💺": "seat",
	"🙈": "see-no-evil monkey",
	"🌱": "seedling",
	"🤳": "selfie",
	"🤳🏿": "selfie: dark skin tone",
	"🤳🏻": "selfie: light skin tone",
	"🤳🏽": "selfie: medium skin tone",
	"🤳🏾": "selfie: medium-dark skin tone",
	"🤳🏼": "selfie: medium-light skin tone",
	"🕖": "seven o'clock",
	"🕢": "seven-thirty",
	"🪡": "sewing needle",
	"🫨": "shaking face",
	"🥘": "shallow pan of food",
	"☘️": "shamrock",
	"🦈": "shark",
	"🍧": "shaved ice",
	"🌾": "sheaf of rice",
	"🛡️": "shield",
	"⛩️": "shinto shrine",
	"🚢": "ship",
	"🌠": "shooting star",
	"🛍️": "shopping bags",
	"🛒": "shopping cart",
	"🍰": "shortcake",
	"🩳": "shorts",
	"🚿": "shower",
	"🦐": "shrimp",
	"🔀": "shuffle tracks button",
	"🤫": "shushing face",
	"🤘": "sign of the horns",
	"🤘🏿": "sign of the horns: dark skin tone",
	"🤘🏻": "sign of the horns: light skin tone",
	"🤘🏽": "sign of the horns: medium skin tone",
	"🤘🏾": "sign of the horns: medium-dark skin tone",
	"🤘🏼": "sign of the horns: medium-light skin tone",
	"🕕": "six o'clock",
	"🕡": "six-thirty",
	"🛹": "skateboard",
	"⛷️": "skier",
	"🎿": "skis",
	"💀": "skull",
	"☠️": "skull and crossbones",
	"🦨": "skunk",
	"🛷": "sled",
	"😴": "sleeping face",
	"😪": "sleepy face",
	"🙁": "slightly frowning face",
	"🙂": "slightly smiling face",
	"🎰": "slot machine",
	"🦥": "sloth",
	"🛩️": "small airplane",
	"🔹": "small blue diamond",
	"🔸": "small orange diamond",
	"😻": "smiling cat with heart-eyes",
	"☺️": "smiling face",
	"😇": "smiling face with halo",
	"😍": "smiling face with heart-eyes",
	"🥰": "smiling face with hearts",
	"😈": "smiling face with horns",
	"🤗": "smiling face with open hands",
	"😊": "smiling face with smiling eyes",
	"😎": "smiling face with sunglasses",
	"🥲": "smiling face with tear",
	"😏": "smirking face",
	"🐌": "snail",
	"🐍": "snake",
	"🤧": "sneezing face",
	"🏔️": "snow-capped mountain",
	"🏂": "snowboarder",
	"🏂🏿": "snowboarder: dark skin tone",
	"🏂🏻": "snowboarder: light skin tone",
	"🏂🏽": "snowboarder: medium skin tone",
	"🏂🏾": "snowboarder: medium-dark skin tone",
	"🏂🏼": "snowboarder: medium-light skin tone",
	"❄️": "snowflake",
	"☃️": "snowman",
	"⛄": "snowman without snow",
	"🧼": "soap",
	"⚽": "soccer ball",
	"🧦": "socks",
	"🍦": "soft ice cream",
	"🥎": "softball",
	"♠️": "spade suit",
	"🍝": "spaghetti",
	"❇️": "sparkle",
	"🎇": "sparkler",
	"✨": "sparkles",
	"💖": "sparkling heart",
	"🙊": "speak-no-evil monkey",
	"🔊": "speaker high volume",
	"🔈": "speaker low volume",
	"🔉": "speaker medium volume",
	"🗣️": "speaking head",
	"💬": "speech balloon",
	"🚤": "speedboat",
	"🕷️": "spider",
	"🕸️": "spider web",
	"🗓️": "spiral calendar",
	"🗒️": "spiral notepad",
	"🐚": "spiral shell",
	"🧽": "sponge",
	"🥄": "spoon",
	"🚙": "sport utility vehicle",
	"🏅": "sports medal",
	"🐳": "spouting whale",
	"🦑": "squid",
	"😝": "squinting face with tongue",
	"🏟️": "stadium",
	"⭐": "star",
	"☪️": "star and crescent",
	"✡️": "star of David",
	"🤩": "star-struck",
	"🚉": "station",
	"🍜": "steaming bowl",
	"🩺": "stethoscope",
	"⏹️": "stop button",
	"🛑": "stop sign",
	"⏱️": "stopwatch",
	"📏": "straight ruler",
	"🍓": "strawberry",
	"🎙️": "studio microphone",
	"🥙": "stuffed flatbread",
	"☀️": "sun",
	"⛅": "sun behind cloud",
	"🌥️": "sun behind large cloud",
	"🌦️": "sun behind rain cloud",
	"🌤️": "sun behind small cloud",
	"🌞": "sun with face",
	"🌻": "sunflower",
	"🕶️": "sunglasses",
	"🌅": "sunrise",
	"🌄": "sunrise over mountains",
	"🌇": "sunset",
	"🦸": "superhero",
	"🦸🏿": "superhero: dark skin tone",
	"🦸🏻": "superhero: light skin tone",
	"🦸🏽": "superhero: medium skin tone",
	"🦸🏾": "superhero: medium-dark skin tone",
	"🦸🏼": "superhero: medium-light skin tone",
	"🦹": "supervillain",
	"🦹🏿": "supervillain: dark skin tone",
	"🦹🏻": "supervillain: light skin tone",
	"🦹🏽": "supervillain: medium skin tone",
	"🦹🏾": "supervillain: medium-dark skin tone",
	"🦹🏼": "supervillain: medium-light skin tone",
	"🍣": "sushi",
	"🚟": "suspension railway",
	"🦢": "swan",
	"💦": "sweat droplets",
	"🕍": "synagogue",
	"💉": "syringe",
	"👕": "t-shirt",
	"🌮": "taco",
	"🥡": "takeout box",
	"🫔": "tamale",
	"🎋": "tanabata tree",
	"🍊": "tangerine",
	"🚕": "taxi",
	"🍵": "teacup without handle",
	"🫖": "teapot",
	"📆": "tear-off calendar",
	"🧸": "teddy bear",
	"☎️": "telephone",
	"📞": "telephone receiver",
	"🔭": "telescope",
	"📺": "television",
	"🕙": "ten o'clock",
	"🕥": "ten-thirty",
	"🎾": "tennis",
	"⛺": "tent",
	"🧪": "test tube",
	"🌡️": "thermometer",
	"🤔": "thinking face",
	"🩴": "thong sandal",
	"💭": "thought balloon",
	"🧵": "thread",
	"🕒": "three o'clock",
	"🕞": "three-thirty",
	"👎": "thumbs down",
	"👎🏿": "thumbs down: dark skin tone",
	"👎🏻": "thumbs down: light skin tone",
	"👎🏽": "thumbs down: medium skin tone",
	"👎🏾": "thumbs down: medium-dark skin tone",
	"👎🏼": "thumbs down: medium-light skin tone",
	"👍": "thumbs up",
	"👍🏿": "thumbs up: dark skin tone",
	"👍🏻": "thumbs up: light skin tone",
	"👍🏽": "thumbs up: medium skin tone",
	"👍🏾": "thumbs up: medium-dark skin tone",
	"👍🏼": "thumbs up: medium-light skin tone",
	"🎫": "ticket",
	"🐅": "tiger",
	"🐯": "tiger face",
	"⏲️": "timer clock",
	"😫": "tired face",
	"🚽": "toilet",
	"🍅": "tomato",
	"👅": "tongue",
	"🧰": "toolbox",
	"🦷": "tooth",
	"🪥": "toothbrush",
	"🎩": "top hat",
	"🌪️": "tornado",
	"🖲️": "trackball",
	"🚜": "tractor",
	"™️": "trade mark",
	"🚆": "train",
	"🚊": "tram",
	"🚋": "tram car",
	"⚧️": "transgender symbol",
	"🚩": "triangular flag",
	"📐": "triangular ruler",
	"🔱": "trident emblem",
	"🧌": "troll",
	"🚎": "trolleybus",
	"🏆": "trophy",
	"🍹": "tropical drink",
	"🐠": "tropical fish",
	"🎺": "trumpet",
	"🌷": "tulip",
	"🥃": "tumbler glass",
	"🦃": "turkey",
	"🐢": "turtle",
	"🕛": "twelve o'clock",
	"🕧": "twelve-thirty",
	"💕": "two hearts",
	"🕑": "two o'clock",
	"🐫": "two-hump camel",
	"🕝": "two-thirty",
	"☂️": "umbrella",
	"⛱️": "umbrella on ground",
	"☔": "umbrella with rain drops",
	"😒": "unamused face",
	"🦄": "unicorn",
	"🔓": "unlocked",
	"⬆️": "up arrow",
	"↕️": "up-down arrow",
	"↖️": "up-left arrow",
	"↗️": "up-right arrow",
	"🙃": "upside-down face",
	"🔼": "upwards button",
	"🧛": "vampire",
	"🧛🏿": "vampire: dark skin tone",
	"🧛🏻": "vampire: light skin tone",
	"🧛🏽": "vampire: medium skin tone",
	"🧛🏾": "vampire: medium-dark skin tone",
	"🧛🏼": "vampire: medium-light skin tone",
	"🚦": "vertical traffic light",
	"📳": "vibration mode",
	"✌️": "victory hand",
	"✌🏿": "victory hand: dark skin tone",
	"✌🏻": "victory hand: light skin tone",
	"✌🏽": "victory hand: medium skin tone",
	"✌🏾": "victory hand: medium-dark skin tone",
	"✌🏼": "victory hand: medium-light skin tone",
	"📹": "video camera",
	"🎮": "video game",
	"📼": "videocassette",
	"🎻": "violin",
	"🌋": "volcano",
	"🏐": "volleyball",
	"🖖": "vulcan salute",
	"🖖🏿": "vulcan salute: dark skin tone",
	"🖖🏻": "vulcan salute: light skin tone",
	"🖖🏽": "vulcan salute: medium skin tone",
	"🖖🏾": "vulcan salute: medium-dark skin tone",
	"🖖🏼": "vulcan salute: medium-light skin tone",
	"🧇": "waffle",
	"🌘": "waning crescent moon",
	"🌖": "waning gibbous moon",
	"⚠️": "warning",
	"🗑️": "wastebasket",
	"⌚": "watch",
	"🐃": "water buffalo",
	"🚾": "water closet",
	"🔫": "water pistol",
	"🌊": "water wave",
	"🍉": "watermelon",
	"👋": "waving hand",
	"👋🏿": "waving hand: dark skin tone",
	"👋🏻": "waving hand: light skin tone",
	"👋🏽": "waving hand: medium skin tone",
	"👋🏾": "waving hand: medium-dark skin tone",
	"👋🏼": "waving hand: medium-light skin tone",
	"〰️": "wavy dash",
	"🌒": "waxing crescent moon",
	"🌔": "waxing gibbous moon",
	"🙀": "weary cat",
	"😩": "weary face",
	"💒": "wedding",
	"🐋": "whale",
	"🛞": "wheel",
	"☸️": "wheel of dharma",
	"♿": "wheelchair symbol",
	"🦯": "white cane",
	"⚪": "white circle",
	"❕": "white exclamation mark",
	"🏳️": "white flag",
	"💮": "white flower",
	"🤍": "white heart",
	"⬜": "white large square",
	"◻️": "white medium square",
	"◽": "white medium-small square",
	"❔": "white question mark",
	"▫️": "white small square",
	"🔳": "white square button",
	"🥀": "wilted flower",
	"🎐": "wind chime",
	"🌬️": "wind face",
	"🪟": "window",
	"🍷": "wine glass",
	"🪽": "wing",
	"😉": "winking face",
	"😜": "winking face with tongue",
	"🛜": "wireless",
	"🐺": "wolf",
	"👩": "woman",
	"👫": "woman and man holding hands",
	"👫🏿": "woman and man holding hands: dark skin tone",
	"👫🏻": "woman and man holding hands: light skin tone",
	"👫🏽": "woman and man holding hands: medium skin tone",
	"👫🏾": "woman and man holding hands: medium-dark skin tone",
	"👫🏼": "woman and man holding hands: medium-light skin tone",
	"💃": "woman dancing",
	"💃🏿": "woman dancing: dark skin tone",
	"💃🏻": "woman dancing: light skin tone",
	"💃🏽": "woman dancing: medium skin tone",
	"💃🏾": "woman dancing: medium-dark skin tone",
	"💃🏼": "woman dancing: medium-light skin tone",
	"🧕": "woman with headscarf",
	"🧕🏿": "woman with headscarf: dark skin tone",
	"🧕🏻": "woman with headscarf: light skin tone",
	"🧕🏽": "woman with headscarf: medium skin tone",
	"🧕🏾": "woman with headscarf: medium-dark skin tone",
	"🧕🏼": "woman with headscarf: medium-light skin tone",
	"👢": "woman's boot",
	"👚": "woman's clothes",
	"👒": "woman's hat",
	"👡": "woman's sandal",
	"👩🏿": "woman: dark skin tone",
	"👩🏻": "woman: light skin tone",
	"👩🏽": "woman: medium skin tone",
	"👩🏾": "woman: medium-dark skin tone",
	"👩🏼": "woman: medium-light skin tone",
	"👭": "women holding hands",
	"👭🏿": "women holding hands: dark skin tone",
	"👭🏻": "women holding hands: light skin tone",
	"👭🏽": "women holding hands: medium skin tone",
	"👭🏾": "women holding hands: medium-dark skin tone",
	"👭🏼": "women holding hands: medium-light skin tone",
	"🚺": "women's room",
	"🪵": "wood",
	"🥴": "woozy face",
	"🗺️": "world map",
	"🪱": "worm",
	"😟": "worried face",
	"🎁": "wrapped gift",
	"🔧": "wrench",
	"✍️": "writing hand",
	"✍🏿": "writing hand: dark skin tone",
	"✍🏻": "writing hand: light skin tone",
	"✍🏽": "writing hand: medium skin tone",
	"✍🏾": "writing hand: medium-dark skin tone",
	"✍🏼": "writing hand: medium-light skin tone",
	"🩻": "x-ray",
	"🧶": "yarn",
	"🥱": "yawning face",
	"🟡": "yellow circle",
	"💛": "yellow heart",
	"🟨": "yellow square",
	"💴": "yen banknote",
	"☯️": "yin yang",
	"🪀": "yo-yo",
	"🤪": "zany face",
	"🦓": "zebra",
	"🤐": "zipper-mouth face",
	"🧟": "zombie",
} as const

export type SymbolEmoji = keyof typeof SYMBOL_EMOJIS
export type SymbolEmojiName = (typeof SYMBOL_EMOJIS)[keyof typeof SYMBOL_EMOJIS]
